### ISSUE TITLE
Error in running kapture_download_dataset.py update

### ISSUE THREAD

**Issue by shuimushan** [naver/kapture-localization#35]
I wanna to download the datasets mentioned in benchmark.adoc and get the error below. I thought it might be the certificate verification problem and set requests.get(index_remote_url, allow_redirects=True,verify=False), but it didn't work. So what's the problem with it? Could you please give me some ideas about how to solve it?

kapture_download_dataset.py update
INFO    ::downloader: updating dataset list from https://github.com/naver/kapture/raw/main/dataset ...
/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
CRITICAL::downloader: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /naver/kapture/raw/main/dataset/kapture_dataset_index.yaml (Caused by SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2570)')))
Traceback (most recent call last):
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2570)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /naver/kapture/raw/main/dataset/kapture_dataset_index.yaml (Caused by SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2570)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 643, in <module>
    sys.exit(kapture_download_dataset_cli())
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 638, in kapture_download_dataset_cli
    raise e
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 633, in kapture_download_dataset_cli
    return kapture_download_dataset(args, index_filepath)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 510, in kapture_download_dataset
    r = requests.get(index_remote_url, allow_redirects=True,verify=False)#edit:verify=False
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /naver/kapture/raw/main/dataset/kapture_dataset_index.yaml (Caused by SSLError(SSLError(1, '[

**Comment by jujumo** [comment]
Whats your OS ?
Can you access the url from your web browser ?
https://raw.githubusercontent.com/naver/kapture/main/dataset/kapture_dataset_index.yaml

**Comment by shuimushan** [comment]
> Whats your OS ? Can you access the url from your web browser ? https://raw.githubusercontent.com/naver/kapture/main/dataset/kapture_dataset_index.yaml

That's it! Thank you very much!!! And I solved this problem through following the instructions here ( https://blog.csdn.net/m0_52650517/article/details/119831630 )

**Comment by jujumo** [comment]
thanks for the instructions, it might help others.
