### ISSUE TITLE
Permission denied when downloading "GangnamStation_B2" dataset

### ISSUE THREAD

**Issue by shuimushan** [naver/kapture-localization#36]
I run the installation code , and get the info below:

kapture_download_dataset.py install  "GangnamStation_B2*"
INFO    ::downloader: 11 dataset will be installed.
INFO    ::downloader: GangnamStation_B2_release_mapping: starting installation  ...
INFO    ::downloader: /home/wanshanshan16/kapture_datasets already exists: skipped
INFO    ::downloader: GangnamStation_B2_release_mapping install: successful
INFO    ::downloader: GangnamStation_B2_release_mapping_lidar_only: starting installation  ...
INFO    ::downloader: /home/wanshanshan16/kapture_datasets already exists: skipped
INFO    ::downloader: GangnamStation_B2_release_mapping_lidar_only install: successful
INFO    ::downloader: GangnamStation_B2_release_test: starting installation  ...
INFO    ::downloader: GangnamStation_B2_release_test.tar.gz is already downloaded.
CRITICAL::downloader: [Errno 13] Permission denied: '/home/wanshanshan16/kapture_datasets/GangnamStation/LICENSE.txt'
Traceback (most recent call last):
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 643, in <module>
    sys.exit(kapture_download_dataset_cli())
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 638, in kapture_download_dataset_cli
    raise e
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 633, in kapture_download_dataset_cli
    return kapture_download_dataset(args, index_filepath)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 540, in kapture_download_dataset
    status = dataset.install(force_overwrite=args.force, no_cleaning=args.no_cleaning)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/bin/kapture_download_dataset.py", line 354, in install
    untar_file(self._archive_filepath, self._install_dir.install_root_path)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/site-packages/kapture/converter/downloader/archives.py", line 23, in untar_file
    archive.extractall(install_dirpath)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/wanshanshan16/miniconda3/envs/py3.7_torch1.7.1/lib/python3.7/tarfile.py", line 2155, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/home/wanshanshan16/kapture_datasets/GangnamStation/LICENSE.txt'

After running the code, I got data structure below. So is there any thing wrong with my installation? How can I solve it?
![to_show](https://user-images.githubusercontent.com/61351203/207744513-17a9cfd6-a8d6-4dec-b6cd-fa03e6801cbc.png)

**Comment by shuimushan** [comment]
Well, the solutions are quite simple. The problem was with the locked txt. Just sudo chmod -R 777 LICENSE.txt & kapture_readme.txt and it helps.
