### ISSUE TITLE
ValueError: operation parameter must be str

### ISSUE THREAD

**Issue by bixiaopeng0** [naver/kapture-localization#7]
Hi,
I meet a question when I run kapture_pipeline_localize.py, do you know how to solve it,thanks
the error messages is
`Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/kapture_env/bin/kapture_run_colmap_gv.py", line 4, in <module>
    __import__('pkg_resources').run_script('kapture-localization==0.0.3', 'kapture_run_colmap_gv.py')
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_run_colmap_gv.py", line 156, in <module>
    run_colmap_gv_command_line()
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_run_colmap_gv.py", line 152, in run_colmap_gv_command_line
    run_colmap_gv(args.input, args.output, args.colmap_binary, args.pairsfile_path, args.skip, args.force)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_run_colmap_gv.py", line 41, in run_colmap_gv
    force)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_run_colmap_gv.py", line 83, in run_colmap_gv_from_loaded_data
    export_two_view_geometry=False)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture/converter/colmap/database_extra.py", line 615, in kapture_to_colmap
    colmap_camera_ids = add_cameras_to_database(kapture_data.sensors, database)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture/converter/colmap/database_extra.py", line 346, in add_cameras_to_database
    prior_focal_length=prior_focal_length)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture/converter/colmap/database.py", line 166, in add_camera
    prior_focal_length))
ValueError: operation parameter must be str

Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/kapture_env/bin/kapture_pipeline_localize.py", line 4, in <module>
    __import__('pkg_resources').run_script('kapture-localization==0.0.3', 'kapture_pipeline_localize.py')
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/xxx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_pipeline_localize.py", line 363, in <module>
    localize_pipeline_command_line()
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_pipeline_localize.py", line 353, in localize_pipeline_command_line
    args.force)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/EGG-INFO/scripts/kapture_pipeline_localize.py", line 184, in localize_pipeline
    run_python_command(local_run_colmap_gv_path, run_colmap_gv_args, python_binary)
  File "/home/xx/miniconda3/envs/kapture_env/lib/python3.7/site-packages/kapture_localization-0.0.3-py3.7.egg/kapture_localization/utils/subprocess.py", line 67, in run_python_command
    raise ValueError('\nSubprocess Error (Return code:' f' {python_process.returncode} )')
ValueError: 
Subprocess Error (Return code: 1 )
`

**Comment by yocabon** [comment]
Hi,
I cannot reproduce the error.
Do you get it when you run the [tutorial](https://github.com/naver/kapture-localization/blob/main/doc/tutorial.adoc#prepare-data) ?
If you don't, then could you tell me more about the dataset you're using ? (in particular the content of sensors.txt since the error happens when exporting them to the colmap database)

**Comment by bixiaopeng0** [comment]
thanks,I will try again.
